DROP TABLE IF EXISTS `users`;

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL,
    state INT NOT NULL,
    balance INT NOT NULL,
    bill INT NOT NULL
    );