# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x02pb\"E\n\x0b\x43hatRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x11\n\tuserInput\x18\x02 \x01(\t\x12\x11\n\tuserState\x18\x03 \x01(\x05\"-\n\x0c\x43hatResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x05\x32@\n\x0f\x41nswerGenerator\x12-\n\x06\x41nswer\x12\x0f.pb.ChatRequest\x1a\x10.pb.ChatResponse\"\x00\x42\x0cZ\nbackend/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\nbackend/pb'
  _globals['_CHATREQUEST']._serialized_start=18
  _globals['_CHATREQUEST']._serialized_end=87
  _globals['_CHATRESPONSE']._serialized_start=89
  _globals['_CHATRESPONSE']._serialized_end=134
  _globals['_ANSWERGENERATOR']._serialized_start=136
  _globals['_ANSWERGENERATOR']._serialized_end=200
# @@protoc_insertion_point(module_scope)
