# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x02pb\"J\n\x0cHelloRequest\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\x12\x0c\n\x04\x62ill\x18\x04 \x01(\x02\"X\n\x0b\x43hatRequest\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05input\x18\x03 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x04 \x01(\x02\x12\x0c\n\x04\x62ill\x18\x05 \x01(\x02\"/\n\x0cTimerRequest\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x10\n\x08now_time\x18\x02 \x01(\x05\"L\n\x0c\x43hatResponse\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\x12\x0c\n\x04\x62ill\x18\x04 \x01(\x02\x12\x0e\n\x06\x61nswer\x18\x02 \x03(\t\"\x1e\n\rHelloResponse\x12\r\n\x05words\x18\x01 \x03(\t\"m\n\rTimerResponse\x12\r\n\x05state\x18\x01 \x01(\x05\x12\x0f\n\x07is_exit\x18\x02 \x01(\x08\x12\r\n\x05reset\x18\x03 \x01(\x08\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\x02\x12\x0c\n\x04\x62ill\x18\x06 \x01(\x02\x12\x0e\n\x06\x61nswer\x18\x04 \x03(\t2A\n\x05Greet\x12\x38\n\x0fSayHelloService\x12\x10.pb.HelloRequest\x1a\x11.pb.HelloResponse\"\x00\x32<\n\x04\x43hat\x12\x34\n\rAnswerService\x12\x0f.pb.ChatRequest\x1a\x10.pb.ChatResponse\"\x00\x32>\n\x05Timer\x12\x35\n\x0cTimerService\x12\x10.pb.TimerRequest\x1a\x11.pb.TimerResponse\"\x00\x42\x0cZ\nbackend/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\nbackend/pb'
  _globals['_HELLOREQUEST']._serialized_start=18
  _globals['_HELLOREQUEST']._serialized_end=92
  _globals['_CHATREQUEST']._serialized_start=94
  _globals['_CHATREQUEST']._serialized_end=182
  _globals['_TIMERREQUEST']._serialized_start=184
  _globals['_TIMERREQUEST']._serialized_end=231
  _globals['_CHATRESPONSE']._serialized_start=233
  _globals['_CHATRESPONSE']._serialized_end=309
  _globals['_HELLORESPONSE']._serialized_start=311
  _globals['_HELLORESPONSE']._serialized_end=341
  _globals['_TIMERRESPONSE']._serialized_start=343
  _globals['_TIMERRESPONSE']._serialized_end=452
  _globals['_GREET']._serialized_start=454
  _globals['_GREET']._serialized_end=519
  _globals['_CHAT']._serialized_start=521
  _globals['_CHAT']._serialized_end=581
  _globals['_TIMER']._serialized_start=583
  _globals['_TIMER']._serialized_end=645
# @@protoc_insertion_point(module_scope)
